from setuptools import setup, find_packages

setup(
    name="signglove-ksl",
    version="2.1.0",
    description="한국수어(KSL) 실시간 인식 시스템 - 600개 Episode 데이터셋 기반 99.37% 정확도",
    author="Kyle-Riss",
    author_email="kyle.riss@example.com",
    url="https://github.com/Kyle-Riss/KLP-SignGlove",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.20.0",
        "pydantic>=2.0.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "scipy>=1.7.0",
        "tqdm>=4.62.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="sign language, ksl, korean, deep learning, real-time, inference",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
)
