name: Sync External Repositories

on:
  schedule:
    # 매주 월요일 오전 9시에 실행
    - cron: '0 9 * * 1'
  workflow_dispatch: # 수동 실행 가능

jobs:
  sync-external-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout SignGlove repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Sync KLP-SignGlove
      run: |
        # 기존 external 폴더 백업
        if [ -d "external/KLP-SignGlove" ]; then
          mv external/KLP-SignGlove external/KLP-SignGlove_backup
        fi
        
        # 최신 코드 클론
        git clone https://github.com/Kyle-Riss/KLP-SignGlove.git external/KLP-SignGlove
        rm -rf external/KLP-SignGlove/.git
        
        # 변경사항이 있으면 커밋
        if ! git diff --quiet; then
          git add external/KLP-SignGlove/
          git commit -m "Auto-sync KLP-SignGlove repository"
          git push
        fi
    
    - name: Sync SignGlove_HW
      run: |
        # 기존 external 폴더 백업
        if [ -d "external/SignGlove_HW" ]; then
          mv external/SignGlove_HW external/SignGlove_HW_backup
        fi
        
        # 최신 코드 클론
        git clone https://github.com/KNDG01001/SignGlove_HW.git external/SignGlove_HW
        rm -rf external/SignGlove_HW/.git
        
        # 변경사항이 있으면 커밋
        if ! git diff --quiet; then
          git add external/SignGlove_HW/
          git commit -m "Auto-sync SignGlove_HW repository"
          git push
        fi
    
    - name: Cleanup backups
      run: |
        rm -rf external/*_backup
